FROM debian:buster-slim

RUN useradd -m -u 1000 -U -s /bin/sh -d /starfleet starfleet && \
	mkdir -p /starfleet/.local/share && \
	mkdir /data && \
	chown -R starfleet:starfleet /data && \
	ln -s /data /starfleet/.local/share/starfleet && \
	rm -rf /usr/bin /usr/sbin

USER starfleet

# 30333 for parachain p2p
# 30334 for relaychain p2p
# 9933 for RPC call
# 9944 for Websocket
# 9615 for Prometheus (metrics)
EXPOSE 30333 30334 9933 9944 9615

VOLUME ["/data"]

ENTRYPOINT ["/starfleet/starfleet"]